### ISSUE TITLE
Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by kyle-lk** [deepomicslab/DeepHost#2]
2022-08-08 13:21:12.901403: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-08 13:21:12.901437: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Encode sequences...
make predictions...
Traceback (most recent call last):
  File "/home/liukai/biosoft/host_prediction/DeepHost/DeepHost_scripts/DeepHost.py", line 153, in <module>
    main(arguments)
  File "/home/liukai/biosoft/host_prediction/DeepHost/DeepHost_scripts/DeepHost.py", line 129, in main
    model = keras.models.load_model("CNN_species_model.h5")
  File "/home/liukai/biosoft/anaconda3/envs/tensorflow/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/liukai/biosoft/anaconda3/envs/tensorflow/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/liukai/biosoft/anaconda3/envs/tensorflow/lib/python3.9/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

**Comment by wangruohan111** [comment]
Hi, could you please check if "CNN_species_model.h5" and "CNN_genus_model.h5" are under DeepHost_scripts/? If not, please download the models from google drive as described in README.

**Comment by kyle-lk** [comment]
![image](https://user-images.githubusercontent.com/12771990/183346974-db881c22-6876-47a4-9b3e-61deeca78565.png)

yes, I used git-clone to dowload all files

**Comment by kyle-lk** [comment]
![image](https://user-images.githubusercontent.com/12771990/183347555-fdedd4e2-40a4-4aaf-99e3-744ced27f10d.png)

![image](https://user-images.githubusercontent.com/12771990/183347607-47799e0a-fe38-407b-966e-69a9e34c6466.png)

Thank you.  I think the problem is that I did not download the complete h5 file。 There is an error report from git-lfs-clone.

**Comment by wangruohan111** [comment]
These two h5 files are oversized (more than 500 MB for each), and can not be downloaded with "git clone". Could you check the size of your downloaded h5 files? If they are smaller than 500 MB, it seems the models are not downloaded completely. You can either use "git lfs clone" or download them directly for google drive.

**Comment by wangruohan111** [comment]
> ![image](https://user-images.githubusercontent.com/12771990/183347555-fdedd4e2-40a4-4aaf-99e3-744ced27f10d.png)
> 
> ![image](https://user-images.githubusercontent.com/12771990/183347607-47799e0a-fe38-407b-966e-69a9e34c6466.png)
> 
> Thank you. I think the problem is that I did not download the complete h5 file。 There is an error report from git-lfs-clone.

I think that's the problem. If you can not use "git lfs", downloading from Google Drive should work too.

**Comment by kyle-lk** [comment]
![image](https://user-images.githubusercontent.com/12771990/183348814-836681db-81ca-4ba6-93f1-f76d37fc1d9c.png)

Thank you so much! I download h5 file from Google Drive, and fixed the problem

**Comment by wangruohan111** [comment]
That's good. I will close this issue. If there are any problems later, please feel free to open a new issue.
