### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by JEMINA-JOHN** [deepomicslab/DeepHost#3]
2023-11-03 20:54:33.311518: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-03 20:54:33.311588: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-03 20:54:33.311626: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-03 20:54:33.319550: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-03 20:54:34.267320: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Encode sequences...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/content/DeepHost/DeepHost_scripts/DeepHost.py", line 103, in encode_seq
    return encode.matrix_encoding(seq, 5)
  File "encode.pyx", line 57, in encode.matrix_encoding
    return _matrix_encoding(seq, K)
  File "encode.pyx", line 49, in encode._matrix_encoding
    _loc_transfer_matrix(loc_1, 0, K).flatten(), _loc_transfer_matrix(loc_2, 0, K).flatten(),
  File "encode.pyx", line 30, in encode._loc_transfer_matrix
    matrix = np.zeros((2**K, 2**K))
TypeError: 'float' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/DeepHost/DeepHost_scripts/DeepHost.py", line 153, in <module>
    main(arguments)
  File "/content/DeepHost/DeepHost_scripts/DeepHost.py", line 118, in main
    feature_list = pool.map(encode_seq, seq_list) 
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/content/DeepHost/DeepHost_scripts/DeepHost.py", line 103, in encode_seq
    return encode.matrix_encoding(seq, 5)
  File "encode.pyx", line 57, in encode.matrix_encoding
    return _matrix_encoding(seq, K)
  File "encode.pyx", line 49, in encode._matrix_encoding
    _loc_transfer_matrix(loc_1, 0, K).flatten(), _loc_transfer_matrix(loc_2, 0, K).flatten(),
  File "encode.pyx", line 30, in encode._loc_transfer_matrix
    matrix = np.zeros((2**K, 2**K))
TypeError: 'float' object cannot be interpreted as an integer

I am running this tool in Google Colab pro and getting this error. Am i doing something wrong? I only tried running the example file. @wangruohan111

**Comment by wangruohan111** [comment]
Hi,

This error is caused by the Cython compiler version, and the version we have tested is 0.29.

If you have further questions, please feel free to open a new issue or contact me.

Ruohan
